name: Build Container

on:
  push:

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Container
      run: |
        docker build . -t purs:musl

    - name: Run Container
      run: |
        docker run -t 'purs:musl'
